language: ruby
dist: trusty
sudo: required
rvm:
  - 2.2.4
node_js:
  - 6.11.3

branches:
    only:
      - master

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - ./ensure-env-vars-exist.bash
  - pip install --user awscli
  - mkdir ./coverage
  - node -v
  - npm -v
  - sudo apt-get update
# See https://github.com/department-of-veterans-affairs/caseflow/issues/1744 for detail on why we're doing this.
  - wget https://s3-us-gov-west-1.amazonaws.com/dsva-appeals-devops/chromium-chromedriver_53.0.2785.143-0ubuntu0.14.04.1.1145_amd64.deb -O $PWD/chromium-chromedriver.deb
  - sudo dpkg -i $PWD/chromium-chromedriver.deb
  - sudo apt-get install -f
  - sudo apt-get install pdftk
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - cd ./client && npm install --no-optional
  - cd ..


jobs:
  include:
    - stage: test and lint
      env: TEST_CATEGORY=unit
      script:
        - bundle exec rake spec:parallel:setup:unit
        - bundle exec rake spec:parallel:unit
        - aws s3 mv /home/travis/build/department-of-veterans-affairs/caseflow/coverage/.resultset.json s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER/.$TEST_CATEGORY.resultset.json
        - aws s3 sync s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER ./coverage
        - bundle exec rake ci:travis_verify_code_coverage
    - 
      env: TEST_CATEGORY=api
      script:
        - bundle exec rake spec:parallel:setup:api
        - bundle exec rake spec:parallel:api
        - aws s3 mv /home/travis/build/department-of-veterans-affairs/caseflow/coverage/.resultset.json s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER/.$TEST_CATEGORY.resultset.json
        - aws s3 sync s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER ./coverage
        - bundle exec rake ci:travis_verify_code_coverage
    - 
      env: TEST_CATEGORY=certification
      script:
        - bundle exec rake spec:parallel:setup:certification
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - bundle exec rake spec:parallel:certification
        - aws s3 mv /home/travis/build/department-of-veterans-affairs/caseflow/coverage/.resultset.json s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER/.$TEST_CATEGORY.resultset.json
        - aws s3 sync s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER ./coverage
        - bundle exec rake ci:travis_verify_code_coverage
    - 
      env: TEST_CATEGORY=dispatch
      script:
        - bundle exec rake spec:parallel:setup:dispatch
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - bundle exec rake spec:parallel:dispatch
        - aws s3 mv /home/travis/build/department-of-veterans-affairs/caseflow/coverage/.resultset.json s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER/.$TEST_CATEGORY.resultset.json
        - aws s3 sync s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER ./coverage
        - bundle exec rake ci:travis_verify_code_coverage
    - 
      env: TEST_CATEGORY=reader
      script:
        - bundle exec rake spec:parallel:setup:reader
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - bundle exec rake spec:parallel:reader
        - aws s3 mv /home/travis/build/department-of-veterans-affairs/caseflow/coverage/.resultset.json s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER/.$TEST_CATEGORY.resultset.json
        - aws s3 sync s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER ./coverage
        - bundle exec rake ci:travis_verify_code_coverage
    - 
      env: TEST_CATEGORY=other
      script:
        - bundle exec rake spec:parallel:setup:other
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - bundle exec rake spec:parallel:other
        - aws s3 mv /home/travis/build/department-of-veterans-affairs/caseflow/coverage/.resultset.json s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER/.$TEST_CATEGORY.resultset.json
        - aws s3 sync s3://dsva-appeals-travis-builds/build-$TRAVIS_BUILD_NUMBER ./coverage
        - bundle exec rake ci:travis_verify_code_coverage
    - 
      env: TEST_CATEGORY=javascript
      script:
        - cd client
        - npm run build
        - cd ..
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - bundle exec rake konacha:run
        - bundle exec rake mocha
    -
      env: TEST_CATEGORY=linters_and_security
      script:
        - bundle exec rake lint
        - bundle exec rake security
        - cd ./client
        - mv node_modules node_modules_bak && npm install --production --no-optional && npm run build:production
        # Move the non-production node_modules back so that it's cached for next travis test run
        - rm -rf node_modules && mv node_modules_bak node_modules


bundler_args: "--deployment --without development staging production"
cache:
  directories:
    - vendor/bundle
    - client/node_modules

notifications:
  email: false

services:
  - redis-server

group: deprecated-2017Q2
