language: ruby
dist: wily
rvm:
  - 2.3.0

branches:
    only:
      - master

addons:
  sauce_connect: true

# Install PhantomJS 2.0 from source binary, remove once TravisCI environment has PhantomJS 2.0 installed
# see https://github.com/travis-ci/travis-ci/issues/3225 for more details
before_install:
  - mkdir travis-phantomjs
  - wget https://s3-us-west-2.amazonaws.com/va.devops/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs -v

before_script:
  - sudo apt-get install pdftk

script:
  - bundle exec rake

bundler_args: "--without development staging production"
cache:
  directories:
    - vendor/bundle

notifications:
  email: false
