language: ruby
dist: trusty
sudo: required
rvm:
  - 2.2.4

branches:
    only:
      - master

before_install:
  - mkdir travis-node
  - wget https://s3-us-gov-west-1.amazonaws.com/shared-s3/dsva-appeals/node-v6.10.2-linux-x64.tar.xz -O $PWD/travis-node/node-v6.10.2-linux-x64.tar.xz
  - tar xf $PWD/travis-node/node-v6.10.2-linux-x64.tar.xz -C $PWD/travis-node
  - export PATH=$PWD/travis-node/node-v6.10.2-linux-x64/bin:$PATH
  - node -v
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver

before_script:
  - node -v
  - npm -v
  - cd ./client && npm install --no-optional
  - sudo apt-get install pdftk
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:schema:load
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# TODO(jd): Enable parallel tests on travis when we are ready
# This involves adding `bundle exec rake parallel:setup[3]` in the before_script block
# and `bundle exec rake parallel:rspec[3]` in the script block
script:
  - "export CHROME_ARGS=--no-sandbox"
  - bundle exec rake spec
  - bundle exec rake ci:other
  # Move our node modules, then do a production install & webpack build
  # This verifies our production webpack build step is working
  - mv node_modules node_modules_bak && npm install --production --no-optional && npm run build:production
  # Move the non-production node_modules back so that it's cached for next travis test run
  - rm -rf node_modules && mv node_modules_bak node_modules

bundler_args: "--deployment --without development staging production"
cache:
  directories:
    - vendor/bundle
    - client/node_modules

notifications:
  email: false

services:
  - redis-server

group: deprecated-2017Q2