# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Caseflow Docs
email: ""

# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for Caseflow
baseurl: "/caseflow" # required for themes to work in GH Pages for this repo

url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll


# ----- Set defaults for Jekyll Front Matter so we don't have to include `layout: default` for each md file.
defaults:
  -
    scope:
      # Note gotcha: https://github.com/pmarsceill/just-the-docs/issues/472
      path: "batteam" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "batteam/dispatch/*.md"
    values:
      grand_parent: Bat Team
      parent: Caseflow Dispatch
      product: Dispatch


# ----- Mimic GitHub Pages' settings that cannot be changed
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site
# https://jekyllrb.com/docs/configuration/options/
lsi: false
safe: true
# source: [your repo's top level directory]
# incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


# Build settings
# theme: minima
remote_theme: pmarsceill/just-the-docs # https://pmarsceill.github.io/just-the-docs/docs/configuration/
# remote_theme: pages-themes/modernist@v0.2.0

# ----- just-the-docs theme configuration ----
# https://pmarsceill.github.io/just-the-docs/docs/configuration/

# Aux links for the upper right navigation
aux_links:
  "Caseflow on GitHub":
    - "//github.com/department-of-veterans-affairs/caseflow"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page"
gh_edit_repository: "https://github.com/department-of-veterans-affairs/caseflow" # the github URL for your repo
gh_edit_branch: "main-gh-pages" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# -------------------------------------------

collections:
  batteam_items:
    permalink: "/:collection/:path/"
    output: true
    sort_by: product

just_the_docs:
  # Define which collections are used in just-the-docs and to be included in search
  # https://pmarsceill.github.io/just-the-docs/docs/configuration/#document-collections
  collections:
    # batteam_items:
    #   # Give the collection a name
    #   name: "Bat Team"
    #   # Exclude the collection from the navigation
    #   # Supports true or false (default)
    #   nav_exclude: false
    #   # Exclude the collection from the search
    #   # Supports true or false (default)
    #   search_exclude: false

# -------------------------------------------
# Mimic GH Pages: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-remote-theme
  - jekyll-diagrams
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

# ----- plugin configuration
readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: false

# ----- Exclude from processing
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Makefile
  - .github/
  - .*
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Don't delete these files in the destination directory.
# Useful for files that are not generated by jekyll; e.g. files are generated by other tools
keep_files:
  - help
