services:
  appeals-redis:
    container_name: appeals-redis
    image: redis:6.2.6
    ports:
      - "6379:6379"

  appeals-postgres:
    build:
      context: ./docker-bin/pg
      dockerfile: Dockerfile
    container_name: appeals-db
    platform: linux/amd64
    ports:
      - "5432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  appeals-localstack-aws:
    platform: linux/amd64
    container_name: localstack
    image: localstack/localstack:0.14.5
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
    volumes:
      - ./local/sqs/conf:/conf

  appeals-metabase:
    platform: linux/amd64
    container_name: metabase
    build:
      context: metabase
    ports:
      - "3002:3000"

volumes:
  postgresdata:
