version: '3'
services:

  appeals-localstack-aws:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4561-4583:4561-4583"
      - "8082:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs
    volumes:
      - ./local/sqs/conf:/conf
      - ./local/sqs/localstack:/tmp/localstack"

  vacols-db-development:
    container_name: VACOLS_DB-development
    image: vacols_db:latest
    ports:
      - "1521:1521"
    depends_on:
      - appeals-localstack-aws

  appeals-redis:
    container_name: appeals-redis
    image: redis:2.8.23
    ports:
      - "6379:6379"
    depends_on:
      - vacols-db-development

  appeals-postgres:
    image: postgres:11.1
    container_name: appeals-db
    ports:
      - "5432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
    environment:
     - POSTGRES_PASSWORD=postgres
    depends_on:
      - appeals-redis


  # private docker registry and you need to have permissions to use it
  appeals-app:
    image: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/caseflow:latest
    container_name: appeals-app
    ports:
      - "3000:3000"
    depends_on:
      - appeals-redis
      - appeals-postgres
      - vacols-db-development
      - appeals-localstack-aws
    command: /bin/bash -c "./docker-bi"

  appeals-web:
    image: linuxserver/letsencrypt
    container_name: nginx-letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/New_York
      - URL=caseflowdemo.com
      - SUBDOMAINS=www,
      - VALIDATION=http
    volumes:
      - ./local/nginx/config:/config
    ports:
      - 80:80
      - 443:443
    depends_on:
      - appeals-app
    restart: unless-stopped

volumes:
  postgresdata:
