# For reference:
# +--------- Minute (0-59)
# | +------- Hour (0-23)
# | | +----- Day Of Month (1-31)
# | | | +--- Month (1 -12)
# | | | | +- Day Of Week (0-6) (Sunday = 0)
# | | | | |

# Create establish claim task runs every day at 4:30pm
# TODO (sunil) officially remove this from the config
#create_establish_claim_tasks_job:
#  cron: "30 16 * * * America/New_York"
#  class: "CreateEstablishClaimTasksJob"
#  queue: default
#  active_job: true

reassign_old_tasks:
  cron: "1 0 * * * America/New_York"
  class: "ReassignOldTasksJob"
  queue: default
  active_job: true

# This runs 30 min after the create_establish_claim_tasks_job
# TODO (sunil) officially remove this from the config
#prepare_establish_claim_tasks_job:
#  cron: "0 17 * * * America/New_York"
#  class: "PrepareEstablishClaimTasksJob"
#  queue: default
#  active_job: true

# This job is used to debug https://github.com/department-of-veterans-affairs/caseflow/issues/1814
# It is scheduled to run every 5 minute to make sure Sidekiq and Sidekiq Cron
# are both operational. It will be removed once the issue is fixed.
heartbeat_tasks_job:
  cron: "*/5 * * * * America/New_York"
  class: "HeartbeatTasksJob"
  queue: default
  active_job: true

# Disabled until we have a conversation about how to handle VBMS load
# Retrieve all documents for active Reader users every night at midnight
retrieve_documents_for_reader_job:
  cron: "0 21 * * * America/New_York"
  class: "RetrieveDocumentsForReaderJob"
  args:
    limit: 1500
  queue: default
  active_job: true
  disabled: true

# Checks dependecies every 30 seconds(BGS, VACOLS, VBMS, VBMS.FindDocumentSeriesReference)
dependencies_check_job:
  cron: "*/30 * * * * * America/New_York"
  class: "DependenciesCheckJob"
  queue: default
  active_job: true

# This is created to log DependenciesReportService (and to avoid flooding the logs with each browser window request)
dependencies_report_service_log_job:
  cron: "*/30 * * * * * America/New_York"
  class: "DependenciesReportServiceLogJob"
  queue: default
  active_job: true

# Check which apps are out of service and post a reminder to slack, if any, every 3 hours
out_of_service_reminder_job:
  cron: "0 */3 * * * America/New_York"
  class: "OutOfServiceReminderJob"
  queue: default
  active_job: true

