---
openapi: 3.0.2
info:
  title: API V3
  version: v3
servers:
- url: http://localhost:3000
  description: Local Development server
- url: https://appeals.cf.uat.ds.va.gov
  description: UAT/Staging server
paths: {}
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: TOKEN
